### PR TITLE
RM-156486 Release v0.5.2

### PR DESCRIPTION
**Pull request by joecotton-wk**
## Purpose

Adding WK CI so that it builds correctly,

## Solution

High level overview of what was done. This is the roadmap for those who are going to CR.

## Semantic Versioning (check one)

- [ ] The following were changed in a non-backward compatible way and requires a major version bump:
  - _[link to the breaking change in the diff]_
- [ ] Something public was added or changed in backward compatible way, this requires a minor version bump
- [x] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch
      release

## How to QA

- [ ] `go build ./...` runs successfully
- [ ] Build passes
- [ ] Skynet passes
- [ ] Aviary passes
- [ ] Rosie runs her checks

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(40) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>ajv < 6.12.3</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>ansi-regex < 3.0.1</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>async < 2.6.4</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>color-string < 1.5.5</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>cryptiles < 4.1.2</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>deep-extend < 0.5.1</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>diff < 3.5.0</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>extend < 3.0.2</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>fstream < 1.0.12</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>glob-parent < 5.1.2</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>gopkg.in/yaml.v2 < 2.2.8</code> via <code>go.sum</code></li>
<li>1 vulns in <code>hawk < 9.0.1</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>hoek < 4.2.1</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>hosted-git-info < 2.8.9</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>ini < 1.3.6</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>jsdom < 16.5.0</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>json-schema < 0.4.0</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>macaddress < 0.2.9</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>mem < 4.0.0</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>nth-check < 2.0.1</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>nwmatcher < 1.4.4</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>path-parse < 1.0.7</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>postcss < 7.0.36</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>randomatic < 3.0.0</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>react-dom < 16.2.1</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>sshpk < 1.13.2</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>stringstream < 0.0.6</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>underscore < 1.12.1</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>y18n < 3.2.2</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>1 vulns in <code>yargs-parser < 13.1.2</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>10 vulns in <code>handlebars < 4.7.7</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>2 vulns in <code>braces < 2.3.1</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>2 vulns in <code>elliptic < 6.5.4</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>2 vulns in <code>is-svg < 4.3.0</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>2 vulns in <code>js-yaml < 3.13.1</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>2 vulns in <code>node-fetch < 2.6.7</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>3 vulns in <code>minimist < 1.2.6</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>3 vulns in <code>ua-parser-js < 0.7.24</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>6 vulns in <code>tar < 4.4.18</code> via <code>webui/internal/assets/yarn.lock</code></li>
<li>7 vulns in <code>lodash < 4.17.21</code> via <code>webui/internal/assets/yarn.lock</code></li>
</details>
<details>
<summary>(1) Security relevant changes were detected</summary>
<li>Watched file <code>aviary.yaml</code> added</li>
</details>

## Action Items
* Request infosec review via Slack: #support-infosec
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=work">this Splunk dashboard</a> for more CVE details
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by ryancurtin-wk — APPROVED** [review]

**Comment by joecotton-wk** [comment]
Test comment to see if Rosie is listening

**Comment by joecotton-wk** [comment]
Rosie please try again

**Comment by joecotton-wk** [comment]
QA +1

**Comment by joecotton-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
